- mkdocs.yml
> Update manual URL

- docs/faq.md
- docs/index.md
- docs/known-issues.md
- mkdocs.yml
- Related issues: None
Minor typo corrections and sentence structure updates for documentation.
> Minor grammatical updates

- docs/partials/footer.html
- docs/theme/partials/main.html
> Theme update

- docs/theme/main.html
> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
> Updated telemetry string

- docs/faq.md
- mkdocs.yml
> Documentation fix

- docs/compose/add-addons.md
- docs/compose/custgen-dependencies.md
- docs/compose/index.md
- docs/compose/prompting.md
- docs/contribution-guidelines.md
- docs/faq.md
- docs/recipes/deploy-custom-code.md
- Related issues: None
Minor corrections for typos and sentence structure.
> Doc updates

- docs/recipes/inject-gulp-tasks.md
- generators/addons/templates/addonConfig.json
- generators/handlebars/templates/gulpfile.js
- lib/util.js
- package-lock.json
- package.json
Minor updates on gulp tasks and final tests.
> Minor updates on gulp tasks and final tests.

- lib/pnpsays.js
> Updated pnpsay

- lib/pnpsays.js
- package-lock.json
- package.json
The first release version of the community generator
> Release version

- README.md
> Update Readme table

- README.md
> Documentation fixed

- README.md
- app/index.js
- app/subGenerators.js
- docs/index.md
- generators/addons/index.js
- generators/addons/promptConfig.js
- generators/addons/templates/addonConfig.json
- generators/handlebars/index.js
- lib/patch.js
- lib/patch/utilities.js
- lib/pnpsays.js
- lib/telemetry.js
- lib/util.js
- mocha.opts
- package-lock.json
- package.json
Contains support for the following new libraries.
- [@pnp/spfx-property-controls](https://sharepoint.github.io/sp-dev-fx-property-controls/)
- [@pnp/spfx-controls-react](https://sharepoint.github.io/sp-dev-fx-controls-react/)
> Preparation for Release 1.1.0

- generators/addons/promptConfig.js
> Update configuration for react

- docs/known-issues.md
> Stf bauer patch 1

- lib/util.js
- package-lock.json
- package.json
- Related issues: fixes #84
Fixed error when creating solution in subdirectory solving #84.
> Fixed error when creating solution in subdirectory

- .circleci/config.yml
- generators/vuejs/templates/gulpfile.js
- Related issues: fixes #98 
- Mocha Test Update
- Bugfix for issue #98
> Mocha Test update, Bugfix #98

- generators/angularelements/index.js
- generators/angularelements/promptConfig.js
- lib/util.js
- package-lock.json
- package.json
Fixed bug with project name in Angular Elements generator
> Fixed bug with project name in Angular Elements generator

- docs/known-issues.md
- Related issues: mentioned in #113
Added known issue in Angular Elements generator (#113) to the documentation
> Added known issue in Angular Elements generator to the documentation

- generators/handlebars/templates/gulpfile.js
- Related issues: fixes #121
Fixed Handlebars generator
> Fixed Handlebars generator (#121)

- docs/index.md
Bundel > Bundle
Small spelling fix that triggered my OCD while reading
> Small OCD spelling fix

- app/index.js
- docs/howtos/continuousintegration.md
- generators/addons/index.js
- Related issues: related #155 
Hey @StfBauer it seems that the documentation got lost in the manual merge. I cherry-picked it based on a fresh branch from dev.
> added documentation regarding the continuous integration

- generators/addons/index.js
- generators/addons/templates/addonConfig.json
- generators/addons/templates/tools/pre-version.js
- generators/handlebars/templates/addonConfig.json
- generators/vuejs/templates/addonConfig.json
- lib/pnpsays.js
- package-lock.json
- package.json
- tools/reference-check/addons/package.json
- tools/reference-check/handlebars/package.json
- tools/reference-check/vuejs/package.json
- Update additional dependencies
- New script npm script for 'perversion' to update package-solution and teams manifest.json
> 'npm version' script and dependency updates

- app/index.js
- app/promptConfig.js
- docs/index.md
- [x ] Bugfix
Fixes that were preventing the --environment command line variable from working, and also causing a hang if an invalid input value for the --environment command line variable
> Fixed --environment command-line option

- app/index.js
- app/promptConfig.js
- generators/angularelements/promptConfig.js
- package-lock.json
- package.json
- Related issues: fixes #168, fixes #169
Upgrade to @microsoft/generator-sharepoint 1.8.0
> Upgrade to @microsoft/generator-sharepoint 1.8.0

- generators/vuejs/index.js
- package-lock.json
- package.json
Upgrade to @pnp/office365-cli 1.20.0 - Bugfix to upgrade projects to @microsoft/generator-sharepoint 1.8.2
> Upgrade to @pnp/office365-cli 1.20.0

- generators/addons/templates/azure-pipelines-notesting.yml
- generators/addons/templates/azure-pipelines.yml
- Related issues: 
- upgraded to node 10 for pipeline definition (spfx 1.8.2 brings support)
- other minor fixes in pipeline definition
> upgraded devops pipeline definition to node 10 and other minor improvements

- app/promptConfig.js
- generators/addons/index.js
- generators/addons/promptConfig.js
- generators/addons/templates/addonConfig.json
- generators/angularelements/promptConfig.js
- generators/angularelements/templates/spfx/library-spo/{componentClassName}.ts
- generators/angularelements/templates/spfx/webpart-spo/{componentClassName}.ts
- generators/handlebars/templates/spfx/library-spo/{componentClassName}.ts
- generators/handlebars/templates/spfx/webpart-spo/{componentClassName}.ts
- generators/vuejs/index.js
- generators/vuejs/templates/addonConfig.json
- generators/vuejs/templates/spfx/library-spo/{componentClassName}.ts
- generators/vuejs/templates/spfx/webpart-spo/{componentClassName}.ts
- lib/util.js
- package-lock.json
- package.json
- tools/reference-check/addons/package.json
- tools/reference-check/package.json
- tools/reference-check/vuejs/package.json
- tools/spfx/library-spo/{componentClassName}.ts
- tools/spfx/webpart-spo/{componentClassName}.ts
- Related issues: fixes #191 , partially #Y, mentioned in #Z
- Upgrade to SPFx 1.9.1
- Angular v6, v7 support added
- SPFx-uifabric-themes add-on added
- Reference updates of add-ons and framework generator
> Version upgrade to SPFx 1.9.1

- docs/usage.md
Addresses issue #197
Improved documentation for `npm version`
> Improved npm version part of Usage doc

- docs/howtos/continuousintegration.md
- generators/addons/index.js
- generators/addons/templates/addonConfig.json
- generators/addons/templates/azure-pipelines-notesting.yml
- generators/addons/templates/azure-pipelines.yml
- generators/addons/templates/jest.config.json
- package-lock.json
On the devops side this adds:
- better unit test and coverage reporting integration with azure devops
- updated jest-junit dependency
- added dependencies caching
- switched to ubuntu agent for better performance
> Devops: better unit testing reporting and pipeline caching 

- generators/addons/index.js
- generators/addons/promptConfig.js
- generators/addons/templates/addonConfig.json
- lib/util.js
- package-lock.json
- package.json
- Integrates [lodash](https://lodash.com)
> Lodash integration for SPO and SharePoint 2019 projects

- docs/howtos/continuousintegration.md
- Related issues: fixes #220
Fixes a link to sample content
> documentation fix broken link

- app/index.js
- app/promptConfig.js
- docs/release-notes.md
- generators/addons/templates/addonConfig.json
- generators/vuejs/index.js
- lib/util.js
- package-lock.json
- Related issues: fixes #232
- Removal of VueJS for 2019 projects due limitation caused by SPFx 1.4.1
- #Bugfix #232: Problem in Scaffolding rerun detection.
> Update to version 1.11.1

- docs/features.md
> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_
> Updated typo

- docs/release-notes.md
- lib/util.js
- Related issues: fixes #263
Incorrect version check during adding a new web part
> Bugfix #263: Incorrect version check during adding new web part

- app/index.js
- package-lock.json
- package.json
- test/testdefinitions/angularelements/angularelements.onprem.js
- test/testdefinitions/angularelements/angularelements.spo.js
- test/testdefinitions/handlebars/handlebars.onprem.js
- test/testdefinitions/handlebars/handlebars.spo.js
- test/testdefinitions/knockout.plus/knockout.onprem.js
- test/testdefinitions/knockout.plus/knockout.spo.js
- test/testdefinitions/knockout/knockout.onprem.js
- test/testdefinitions/knockout/knockout.spo.js
- test/testdefinitions/noframework.plus/noframework.onprem.js
- test/testdefinitions/noframework.plus/noframework.spo.js
- test/testdefinitions/noframework/noframework.onprem.js
- test/testdefinitions/noframework/noframework.spo.js
- test/testdefinitions/reactjs.plus/react.onprem.js
- test/testdefinitions/reactjs.plus/react.spo.js
- test/testdefinitions/reactjs/react.onprem.js
- test/testdefinitions/reactjs/react.spo.js
- test/testdefinitions/vuejs/vuejs.onprem.js
- test/testdefinitions/vuejs/vuejs.spo.js
- tools/test-engine/coreTestDefinition.js
- Related issues: fixes #268 
Bugfix for #268
> Bugfix for #268

- generators/addons/templates/addonConfig.json
- tools/reference-check/package.json
- Related issues: no
Bump versions of PnP React Controls and PnP Property Controls to the latest version.
> Update PnP React Controls and PnP Property Controls versions

- docs/index.md
Removed duplicate words in the main section.
> Removed duplicate words in docs

- generators/angularelements/templates/angular/src/app/{componentClassNameKebabCase}/{componentClassNameKebabCase}.component.ts
Fixed issues of Property 'description' has no initializer and is not definitely in angular.
> Fixed Property 'description' has no initializer and is not definitely

- docs/compose/prompting.md
> Fixed minor typo

- generators/angularelements/index.js
- lib/util.js
- package.json
- Added support for Angular 13.
- Added support for SPFx 1.13.1
> Added support for angular 13 and SPFx 1.13.1

- .github/workflows/npm-publish.yml
> Update workflow action
